//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public string Mail { get; set; }
        public string ThongTin { get; set; }
    }
}
